package vista;

public class vista_introduccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form vista_introduccion
     */
    public vista_introduccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Introducción");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Explorando el Fascinante Mundo de las Matemáticas\n\nLas matemáticas, a menudo llamadas el lenguaje universal, son una disciplina que ha cautivado a mentes curiosas y apasionadas a lo largo de la historia. Desde los antiguos pueblos que contaban sus rebaños hasta las complejas teorías que impulsan la tecnología moderna, las matemáticas han sido una herramienta esencial para comprender y modelar nuestro mundo.\n\nEn su esencia, las matemáticas son un estudio sistemático de las relaciones, patrones y estructuras que subyacen en todo, desde los movimientos de los planetas en el cielo hasta la forma en que se propagan las ondas en el océano. A través de números, símbolos y ecuaciones, las matemáticas nos brindan las herramientas para resolver problemas, predecir eventos y explorar conceptos abstractos.\n\nEste viaje en el mundo de las matemáticas nos llevará desde los fundamentos de la aritmética y la geometría hasta las profundidades de la teoría de números y el análisis matemático. Exploraremos conceptos como el infinito y la proporción áurea, nos adentraremos en el mundo de la lógica y la probabilidad, y descubriremos cómo las matemáticas se entrelazan con otras disciplinas, como la física, la biología y la informática.\n\nA medida que avanzamos, veremos que las matemáticas no solo son un conjunto de reglas y fórmulas, sino un camino para cultivar el pensamiento crítico, la resolución de problemas y la creatividad. Invito a todos a embarcarse en este emocionante viaje de descubrimiento matemático, donde cada número, cada ecuación y cada concepto nos revelará una nueva capa de comprensión en el tejido de nuestro mundo.\n\n¡Bienvenidos a un mundo donde los números no solo son herramientas, sino también llaves para desbloquear los misterios de la realidad misma!");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
