package vista;

public class vista_principal extends javax.swing.JFrame {
    
    public vista_bienvenidos vistab = null;
    public vista_autor vistaa = null;
    public vista_introduccion vistai = null;
    public vista_preguntas vistap = null;
    public vista_teoremapitagoras vistas = null;
    public vista_matematicabooleana vistae = null;

    /**
     * Creates new form vista_principal
     */
    public vista_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Presentación = new javax.swing.JMenu();
        Bienvenidos = new javax.swing.JMenuItem();
        Autor = new javax.swing.JMenuItem();
        Introducción = new javax.swing.JMenuItem();
        Actividades = new javax.swing.JMenu();
        Preguntas = new javax.swing.JMenuItem();
        Videos = new javax.swing.JMenu();
        SistemaDigestivo = new javax.swing.JMenuItem();
        AlimentoSaludable = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Presentación.setText("Presentación");

        Bienvenidos.setText("Bienvenidos");
        Bienvenidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BienvenidosActionPerformed(evt);
            }
        });
        Presentación.add(Bienvenidos);

        Autor.setText("Autor");
        Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorActionPerformed(evt);
            }
        });
        Presentación.add(Autor);

        Introducción.setText("Introducción");
        Introducción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducciónActionPerformed(evt);
            }
        });
        Presentación.add(Introducción);

        menuBar.add(Presentación);

        Actividades.setText("Actividades");

        Preguntas.setText("Preguntas");
        Preguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreguntasActionPerformed(evt);
            }
        });
        Actividades.add(Preguntas);

        menuBar.add(Actividades);

        Videos.setText("Videos");

        SistemaDigestivo.setText("Teorema de pitagoras");
        SistemaDigestivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SistemaDigestivoActionPerformed(evt);
            }
        });
        Videos.add(SistemaDigestivo);

        AlimentoSaludable.setText("Matematica Booleana");
        AlimentoSaludable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentoSaludableActionPerformed(evt);
            }
        });
        Videos.add(AlimentoSaludable);

        menuBar.add(Videos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreguntasActionPerformed
        // TODO add your handling code here:
        if ((vistap == null) ||  (vistap.isClosed())) {
            vistap=new vista_preguntas();
            desktopPane.add(vistap);
            vistap.setVisible(true);
        }
    }//GEN-LAST:event_PreguntasActionPerformed

    private void SistemaDigestivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemaDigestivoActionPerformed
        // TODO add your handling code here:
        if ((vistas == null) ||  (vistas.isClosed())) {
            vistas=new vista_teoremapitagoras();
            desktopPane.add(vistas);
            vistas.setVisible(true);
        }
    }//GEN-LAST:event_SistemaDigestivoActionPerformed

    private void BienvenidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BienvenidosActionPerformed
        // TODO add your handling code here:
        if ((vistab == null) ||  (vistab.isClosed())) {
            vistab=new vista_bienvenidos();
            desktopPane.add(vistab);
            vistab.setVisible(true);
        }
    }//GEN-LAST:event_BienvenidosActionPerformed

    private void AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorActionPerformed
        // TODO add your handling code here:
        if ((vistaa == null) ||  (vistaa.isClosed())) {
            vistaa=new vista_autor();
            desktopPane.add(vistaa);
            vistaa.setVisible(true);
        }
    }//GEN-LAST:event_AutorActionPerformed

    private void IntroducciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducciónActionPerformed
        // TODO add your handling code here:
        if ((vistai == null) ||  (vistai.isClosed())) {
            vistai=new vista_introduccion();
            desktopPane.add(vistai);
            vistai.setVisible(true);
        }
    }//GEN-LAST:event_IntroducciónActionPerformed

    private void AlimentoSaludableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentoSaludableActionPerformed
        // TODO add your handling code here:
        if ((vistae == null) ||  (vistae.isClosed())) {
            vistae=new vista_matematicabooleana();
            desktopPane.add(vistae);
            vistae.setVisible(true);
        }
    }//GEN-LAST:event_AlimentoSaludableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new vista_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Actividades;
    private javax.swing.JMenuItem AlimentoSaludable;
    private javax.swing.JMenuItem Autor;
    private javax.swing.JMenuItem Bienvenidos;
    private javax.swing.JMenuItem Introducción;
    private javax.swing.JMenuItem Preguntas;
    private javax.swing.JMenu Presentación;
    private javax.swing.JMenuItem SistemaDigestivo;
    private javax.swing.JMenu Videos;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
